exports_files ([
#    'mono-2.0/mscorlib.dll',
#    'mono-2.0/System.dll',
#    'mono-2.0/System.Core.dll',
#    'mono-4.5/Facades/System.Runtime.dll',
#    'mono-4.5/Facades/System.IO.dll',
#    'mono-2.0/System.Xml.dll',

    'ksp/KSP_Data/Managed/Assembly-CSharp.dll',
    'ksp/KSP_Data/Managed/Assembly-CSharp-firstpass.dll',
    'ksp/KSP_Data/Managed/UnityEngine.dll',
    'ksp/KSP_Data/Managed/UnityEngine.UI.dll',

    'ksp/KSP_Data/Managed/mscorlib.dll',
    'ksp/KSP_Data/Managed/System.dll',
    'ksp/KSP_Data/Managed/System.Core.dll',
    'ksp/KSP_Data/Managed/System.Xml.dll'
])
